# Generated by Django 3.1.4 on 2020-12-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='number_of_subjects',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='lessons_per_week',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='2', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_name',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Computer Science', 'Computer Science'), ('Physics', 'Physics'), ('Russian Language', 'Russian Language')], max_length=30),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=30)),
                ('quantity_of_groups', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='schedule.department')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ManyToManyField(to='schedule.Course'),
        ),
    ]
